/**
 * Example Configuration
 * 
 * Copy this to understand how to configure the backup endpoint in index.html
 * 
 * DO NOT EDIT THIS FILE - it's just an example!
 * Edit the BACKUP_ENDPOINT constant in index.html instead.
 */

// Example configurations for different scenarios:

// 1. Local development (testing on your computer)
const LOCAL_ENDPOINT = "http://localhost:3000/api/backup-survey";

// 2. Production server (your actual website)
const PRODUCTION_ENDPOINT = "https://your-domain.com/api/backup-survey";

// 3. Cloud platform (Heroku, Railway, etc.)
const CLOUD_ENDPOINT = "https://your-app.herokuapp.com/api/backup-survey";

// 4. Disable backup (leave empty)
const DISABLED = "";

// To use in index.html, find this line:
// const BACKUP_ENDPOINT = "";
// 
// And replace with one of the above, for example:
// const BACKUP_ENDPOINT = "https://your-domain.com/api/backup-survey";

